# Generated by Django 2.2.1 on 2021-02-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0014_auto_20210124_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
